# Generated by Django 3.0.14 on 2022-02-03 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^010-?[1-9]\\d{3}-?\\d{4}')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership',
            field=models.CharField(choices=[('User', 'User'), ('Agency', 'Agency')], default='User', max_length=7),
        ),
    ]
