# Generated by Django 3.0.14 on 2022-02-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220203_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avartar',
            field=models.ImageField(blank=True, upload_to='accounts/avartar/%Y/%m/%d'),
        ),
    ]
