# Generated by Django 3.0.14 on 2022-02-19 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220218_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follwer_set',
        ),
        migrations.AddField(
            model_name='user',
            name='follower_set',
            field=models.ManyToManyField(blank=True, related_name='_user_follower_set_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
